import type { Challenge } from "./types";

export const challenges: Challenge[] = [
  {
    id: "hr-01",
    audioSrc: "/audios/hr/e01-feedback.mp3",
    videoSrc: "/videos/hr/e01-feedback.mp4",
    instruction: "default",
    difficulty: "medium",
    points: 2,
  },
  {
    id: "hr-02",
    audioSrc: "/audios/hr/e01-nevermind.mp3",
    videoSrc: "/videos/hr/e01-nevermind.mp4",
    instruction: "default",
    difficulty: "medium",
    points: 2,
  },
  {
    id: "hr-03",
    audioSrc: "/audios/hr/e01-phone.mp3",
    videoSrc: "/videos/hr/e01-phone.mp4",
    instruction: "default",
    difficulty: "medium",
    points: 2,
  },
  {
    id: "hr-04",
    audioSrc: "/audios/hr/e01-shower.mp3",
    videoSrc: "/videos/hr/e01-shower.mp4",
    instruction: "default",
    difficulty: "medium",
    points: 2,
  },
  {
    id: "hr-05",
    audioSrc: "/audios/hr/e01-wait.mp3",
    videoSrc: "/videos/hr/e01-wait.mp4",
    instruction: "default",
    difficulty: "easy",
    points: 1,
  },
  {
    id: "hr-06",
    audioSrc: "/audios/hr/e01-youtube.mp3",
    videoSrc: "/videos/hr/e01-youtube.mp4",
    instruction: "default",
    difficulty: "hard",
    points: 3,
  },
  {
    id: "hr-07",
    audioSrc: "/audios/hr/e02-come-here.mp3",
    videoSrc: "/videos/hr/e02-come-here.mp4",
    instruction: "default",
    difficulty: "easy",
    points: 1,
  },
  {
    id: "hr-08",
    audioSrc: "/audios/hr/e02-genetic.mp3",
    videoSrc: "/videos/hr/e02-genetic.mp4",
    instruction: "default",
    difficulty: "hard",
    points: 3,
  },
  {
    id: "hr-09",
    audioSrc: "/audios/hr/e02-how-many.mp3",
    videoSrc: "/videos/hr/e02-how-many.mp4",
    instruction: "default",
    difficulty: "hard",
    points: 3,
  },
  {
    id: "hr-10",
    audioSrc: "/audios/hr/e02-next-year.mp3",
    videoSrc: "/videos/hr/e02-next-year.mp4",
    instruction: "default",
    difficulty: "easy",
    points: 1,
  },
  {
    id: "hr-11",
    audioSrc: "/audios/hr/e02-no-kiss.mp3",
    videoSrc: "/videos/hr/e02-no-kiss.mp4",
    instruction: "default",
    difficulty: "medium",
    points: 2,
  },
  {
    id: "hr-12",
    audioSrc: "/audios/hr/e02-penthouse.mp3",
    videoSrc: "/videos/hr/e02-penthouse.mp4",
    instruction: "default",
    difficulty: "medium",
    points: 2,
  },
  {
    id: "hr-13",
    audioSrc: "/audios/hr/e03-break.mp3",
    videoSrc: "/videos/hr/e03-break.mp4",
    instruction: "default",
    difficulty: "medium",
    points: 2,
  },
  {
    id: "hr-14",
    audioSrc: "/audios/hr/e03-pick-or.mp3",
    videoSrc: "/videos/hr/e03-pick-or.mp4",
    instruction: "default",
    difficulty: "hard",
    points: 3,
  },
  {
    id: "hr-15",
    audioSrc: "/audios/hr/e03-runner.mp3",
    videoSrc: "/videos/hr/e03-runner.mp4",
    instruction: "first-time",
    difficulty: "easy",
    points: 1,
  },
  {
    id: "hr-16",
    audioSrc: "/audios/hr/e04-ilya-watching.mp3",
    videoSrc: "/videos/hr/e04-ilya-watching.mp4",
    instruction: "default",
    difficulty: "easy",
    points: 1,
  },
  {
    id: "hr-17",
    audioSrc: "/audios/hr/e04-meeting-rose.mp3",
    videoSrc: "/videos/hr/e04-meeting-rose.mp4",
    instruction: "default",
    difficulty: "medium",
    points: 2,
  },
  {
    id: "hr-18",
    audioSrc: "/audios/hr/e04-rose-media.mp3",
    videoSrc: "/videos/hr/e04-rose-media.mp4",
    instruction: "default",
    difficulty: "medium",
    points: 2,
  },
  {
    id: "hr-19",
    audioSrc: "/audios/hr/e04-shane-watching.mp3",
    videoSrc: "/videos/hr/e04-shane-watching.mp4",
    instruction: "default",
    difficulty: "easy",
    points: 1,
  },
  {
    id: "hr-20",
    audioSrc: "/audios/hr/e04-shane.mp3",
    videoSrc: "/videos/hr/e04-shane.mp4",
    instruction: "default",
    difficulty: "hard",
    points: 3,
  },
  {
    id: "hr-21",
    audioSrc: "/audios/hr/e04-stay.mp3",
    videoSrc: "/videos/hr/e04-stay.mp4",
    instruction: "default",
    difficulty: "hard",
    points: 3,
  },
  {
    id: "hr-22",
    audioSrc: "/audios/hr/e04-years.mp3",
    videoSrc: "/videos/hr/e04-years.mp4",
    instruction: "default",
    difficulty: "easy",
    points: 1,
  },
  {
    id: "hr-23",
    audioSrc: "/audios/hr/e05-all-stars.mp3",
    videoSrc: "/videos/hr/e05-all-stars.mp4",
    instruction: "default",
    difficulty: "medium",
    points: 2,
  },
  {
    id: "hr-24",
    audioSrc: "/audios/hr/e05-come-out.mp3",
    videoSrc: "/videos/hr/e05-come-out.mp4",
    instruction: "default",
    difficulty: "hard",
    points: 3,
  },
  {
    id: "hr-25",
    audioSrc: "/audios/hr/e05-how-about.mp3",
    videoSrc: "/videos/hr/e05-how-about.mp4",
    instruction: "first-time",
    difficulty: "hard",
    points: 3,
  },
  {
    id: "hr-26",
    audioSrc: "/audios/hr/e05-plan.mp3",
    videoSrc: "/videos/hr/e05-plan.mp4",
    instruction: "default",
    difficulty: "easy",
    points: 1,
  },
  {
    id: "hr-27",
    audioSrc: "/audios/hr/e05-russian.mp3",
    videoSrc: "/videos/hr/e05-russian.mp4",
    instruction: "default",
    difficulty: "easy",
    points: 1,
  },
  {
    id: "hr-28",
    audioSrc: "/audios/hr/e05-sunshine.mp3",
    videoSrc: "/videos/hr/e05-sunshine.mp4",
    instruction: "second-time",
    difficulty: "easy",
    points: 1,
  },
  {
    id: "hr-29",
    audioSrc: "/audios/hr/e05-tense.mp3",
    videoSrc: "/videos/hr/e05-tense.mp4",
    instruction: "first-time",
    difficulty: "medium",
    points: 2,
  },
  {
    id: "hr-30",
    audioSrc: "/audios/hr/e06-car-end.mp3",
    videoSrc: "/videos/hr/e06-car-end.mp4",
    instruction: "default",
    difficulty: "easy",
    points: 1,
  },
  {
    id: "hr-31",
    audioSrc: "/audios/hr/e06-car-hands.mp3",
    videoSrc: "/videos/hr/e06-car-hands.mp4",
    instruction: "default",
    difficulty: "easy",
    points: 1,
  },
  {
    id: "hr-32",
    audioSrc: "/audios/hr/e06-lake.mp3",
    videoSrc: "/videos/hr/e06-lake.mp4",
    instruction: "second-time",
    difficulty: "medium",
    points: 2,
  },
  {
    id: "hr-33",
    audioSrc: "/audios/hr/e06-proud.mp3",
    videoSrc: "/videos/hr/e06-proud.mp4",
    instruction: "default",
    difficulty: "hard",
    points: 3,
  },
];
